name = "stackdash"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "c6b2ffe078b3cd81ad2b316057d18858"

[[kv_namespaces]]
binding = "ISSUES_KV"
id = "10cb7a42c6c74a98904eb367ff1fccef"

[vars]
# Non-secret env vars (secrets added via `wrangler secret put`)

# Static assets (built frontend)
[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "none"
